package:
  name: workerd
  version: 1.20241214.0
  epoch: 0
  description: The JavaScript / Wasm runtime that powers Cloudflare Workers
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - glibc-dev

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - bash
      - bazelisk
      - bazelisk-default
      - binutils
      - build-base
      - busybox
      - clang-17
      - clang-17-dev
      - gcc-6
      - gnutar
      - libstdc++-6
      - libstdc++-6-dev
      - libtool
      - llvm-libcxx-17
      - llvm-libcxx-17-dev
      - llvm-libcxxabi-17
      - llvm-libunwind-17
      - llvm-lld-17
      - llvm17
      - llvm17-dev
      - posix-libc-utils
      - python3-dev
      - tcl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cloudflare/workerd
      tag: v${{package.version}}
      expected-commit: acdbbecb00aff739e3091bd8f6cc8c4d0ebe8167

  - name: build
    runs: |
      bazel build \
       --config=thin-lto \
       --linkopt='-lc++' --linkopt='-lm' \
       --host_linkopt='-lc++' --host_linkopt='-lm' \
       //src/workerd/server:workerd

  - name: install
    runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mv bazel-bin/src/workerd/server/workerd ${{targets.destdir}}/usr/bin/workerd

  - uses: strip
